
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/transaction-manager-db
    username: transaction-manager-user
    password: transacton-manager-password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect      

  jackson:
    property-naming-strategy: SNAKE_CASE
